// module/client/react/component/VircadiaAsset.tsx
import { useState, useEffect } from "react";
import { useVircadiaQuery } from "../hook/useVircadiaQuery";

export interface VircadiaAssetData {
    arrayBuffer: ArrayBuffer;
    blob: Blob;
    type: string;
    url: string;
}

interface VircadiaAssetProps {
    assetFileName: string;
    onLoad?: (data: VircadiaAssetData) => void;
    onError?: (error: Error) => void;
}

export const VircadiaAsset: React.FC<VircadiaAssetProps> = ({
    assetFileName,
    onLoad,
    onError,
}) => {
    const [assetData, setAssetData] = useState<VircadiaAssetData | null>(null);
    const [error, setError] = useState<Error | null>(null);
    const [loading, setLoading] = useState(true);
    const executeQuery = useVircadiaQuery();

    useEffect(() => {
        const loadAsset = async () => {
            try {
                setLoading(true);
                setError(null);

                // Fetch from database
                const result = await executeQuery<{
                    asset__data__bytea: any;
                    asset__mime_type: string;
                }>({
                    query: `
                        SELECT asset__data__bytea, asset__mime_type
                        FROM entity.entity_assets
                        WHERE general__asset_file_name = $1
                    `,
                    parameters: [assetFileName],
                });

                if (!result.length) {
                    throw new Error(`Asset ${assetFileName} not found`);
                }

                // Process bytea data
                const rawData = result[0].asset__data__bytea;
                const mimeType = result[0].asset__mime_type;

                // Handle bytea data in different formats
                let byteArray: number[] = [];
                if (
                    rawData &&
                    typeof rawData === "object" &&
                    "data" in rawData &&
                    Array.isArray((rawData as any).data)
                ) {
                    byteArray = (rawData as any).data;
                } else if (Array.isArray(rawData)) {
                    byteArray = rawData;
                }

                // Convert to array buffer and blob
                const uint8Array = new Uint8Array(byteArray);
                const arrayBuffer = uint8Array.buffer;
                const blob = new Blob([uint8Array], { type: mimeType });
                const url = URL.createObjectURL(blob);

                const data: VircadiaAssetData = {
                    arrayBuffer,
                    blob,
                    type: mimeType,
                    url,
                };

                setAssetData(data);
                onLoad?.(data);
            } catch (err) {
                const error =
                    err instanceof Error
                        ? err
                        : new Error("Failed to load asset");
                setError(error);
                onError?.(error);
            } finally {
                setLoading(false);
            }
        };

        loadAsset();

        return () => {
            if (assetData?.url) {
                URL.revokeObjectURL(assetData.url);
            }
        };
    }, [assetFileName, executeQuery, onLoad, onError, assetData]);

    return null;
};

// module/client/framework/vue/component/VircadiaAsset.vue
<template>
  <slot
    :asset-data="assetData"
    :loading="loading"
    :error="error"
  ></slot>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch, toRefs } from "vue";

// Import the Vircadia hook - this would need to be adjusted to match your Vue implementation
// Assuming you have a similar hook in your Vue codebase
import { useVircadia } from "../provider/useVircadia";

export interface VircadiaAssetData {
    arrayBuffer: ArrayBuffer;
    blob: Blob;
    type: string;
    url: string;
}

interface Props {
    fileName: string;
}

const props = defineProps<Props>();
const { fileName } = toRefs(props);

const assetData = ref<VircadiaAssetData | null>(null);
const loading = ref(false);
const error = ref<Error | null>(null);

const vircadia = useVircadia();

const loadAsset = async (assetFileName: string) => {
    loading.value = true;
    error.value = null;

    try {
        console.log(`Starting to load asset: ${assetFileName}`);

        // Fetch from database
        const queryResult = await vircadia.query<
            {
                asset__data__bytea: any;
                asset__mime_type: string;
            }[]
        >({
            query: `
        SELECT asset__data__bytea, asset__mime_type
        FROM entity.entity_assets
        WHERE general__asset_file_name = $1
      `,
            parameters: [assetFileName],
            timeoutMs: 100000,
        });

        if (!queryResult.result[0]) {
            throw new Error(`Asset ${assetFileName} not found`);
        }

        // Process bytea data
        const rawData = queryResult.result[0].asset__data__bytea;
        const mimeType = queryResult.result[0].asset__mime_type;

        // Handle bytea data in different formats
        let byteArray: number[] = [];
        if (
            rawData &&
            typeof rawData === "object" &&
            "data" in rawData &&
            Array.isArray((rawData as unknown as any).data)
        ) {
            byteArray = (rawData as unknown as any).data;
        } else if (Array.isArray(rawData)) {
            byteArray = rawData;
        }

        // Convert to array buffer and blob
        const uint8Array = new Uint8Array(byteArray);
        const arrayBuffer = uint8Array.buffer;
        const blob = new Blob([uint8Array], { type: mimeType });
        const url = URL.createObjectURL(blob);

        assetData.value = {
            arrayBuffer,
            blob,
            type: mimeType,
            url,
        };

        console.log(
            `Successfully loaded asset: ${assetFileName}, type: ${mimeType}, size: ${byteArray.length} bytes`,
        );
    } catch (err) {
        console.error(`Error loading asset ${assetFileName}:`, err);
        error.value =
            err instanceof Error ? err : new Error("Failed to load asset");
    } finally {
        loading.value = false;
        console.log(`Finished loading attempt for asset: ${assetFileName}`);
    }
};

// Load the asset when the component mounts or when fileName changes
watch(
    fileName,
    (newFileName) => {
        if (newFileName) {
            // Clean up previous URL if it exists
            if (assetData.value?.url) {
                URL.revokeObjectURL(assetData.value.url);
            }

            loadAsset(newFileName);
        }
    },
    { immediate: true },
);

// Clean up URL object when component unmounts
onUnmounted(() => {
    if (assetData.value?.url) {
        URL.revokeObjectURL(assetData.value.url);
    }
});
</script>
